#!/bin/bash

# Install Bachata Linux from an installation media (CD-ROM, USB disk)
# Copyright (C) 2012 Mikael Ståldal

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

mount_media() {
for dev in /dev/*; do
	if [ -b ${dev} ] ; then 
        if [ ! -L $dev ]; then
        	if mount -t ${FSTYPE} -o ro ${dev} $1 2>/dev/null ; then
          		if [ -f ${1}/bachatalinux.cgz ] ; then
				    MYDEV=${dev}
				    return 0
                else
                 	umount $1
                fi
            fi
        fi
    fi
done
return 1
}

FSTYPE=$1

MEDIAROOT=/media
TARGET=/mnt

echo
echo
echo
echo
echo
echo
echo
echo
echo "Installing Bachata Linux..."

until mount_media ${MEDIAROOT}; do sleep 1; done

install-bachatalinux ${MEDIAROOT}/bachatalinux.cgz ${MYDEV} ${TARGET}
if [ $? != 0 ]; then
	read -p "Unable to mount target, press ENTER to reboot and try again"
	umount ${MEDIAROOT}
    reboot
fi

umount ${MEDIAROOT}
eject -p ${MYDEV}

echo
read -p "Press ENTER to reboot"
reboot

