#!/bin/bash

# Build a Bachata Linux bundle
# Copyright (C) 2012 Mikael Ståldal

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

VERSION="1.0"
ARCH="i386"

usage() 
{
    echo "Usage:"
	cat <<EOT
      --help                   display this help and exit
      --mirror=MIRROR          Debian mirror URL, see http://www.debian.org/mirror/list (required)
      --kernel=kernel          kernel to install
      --include-apt=pkg1,pkg2  additional packages to install using APT, will automatically install dependencies
      --include-deb=filename   additional packages to install from .deb file (can be repeated), will NOT install dependencies
EOT
    exit 1
}

OPTIONS=`getopt --options "" --longoptions help,mirror:,kernel:,include-apt:,include-deb: -n 'bachatalinux-bundle' -- "$@"`
if [ $? != 0 ]; then
    exit 1
fi
eval set -- "$OPTIONS"
while true ; do
	case "$1" in
		--help) usage ;;
		--mirror) MIRROR="$2" ; shift 2 ;;
        --kernel) KERNEL="$2" ; shift 2 ;;
		--include-apt) INCLUDE_APT="${INCLUDE_APT},$2" ; shift 2 ;;
		--include-deb) INCLUDE_DEB="${INCLUDE_DEB} $2" ; shift 2 ;;
		--) shift ; break ;;
		*) echo "Internal error: $1" ; exit 1 ;;
	esac
done
if [ ! ${MIRROR} ]; then usage; fi
if [ ! ${KERNEL} ]; then usage; fi

if [ `id -u` -ne 0 ]; then
	echo "You must be root"
	exit 1
fi

echo "Creating Bachata Linux ${VERSION} bundle for ${ARCH} with kernel ${KERNEL}..."

PWD=`pwd`
TARGET=`mktemp -d --tmpdir=${PWD}`

INCLUDE_DEB="${INCLUDE_DEB} /usr/share/bachatalinux-builder/localepurge-tiny_1.0_all.deb"

debootstrap --variant=minbase \
    --include=netbase,ifupdown,net-tools,isc-dhcp-client,acpi-support-base,acpid,linux-image-${KERNEL},${INCLUDE_APT} \
    squeeze ${TARGET} ${MIRROR}
if [ $? != 0 ]; then
    echo "Installation failed!"
    exit 1
fi

cat <<EOT |ed -s ${TARGET}/var/cache/debconf/config.dat >/dev/null
/Template: debconf\/frontend/
+
c
Value: Teletype
.
wq
EOT

for deb in ${INCLUDE_DEB}; do
    dpkg --root=${TARGET} -i ${deb}
done

rm -rf ${TARGET}/usr/share/man/*
rm -rf ${TARGET}/tmp/*
rm -rf ${TARGET}/var/lib/apt/lists/*
rm -rf ${TARGET}/var/cache/apt/*

mkdir -p ${TARGET}/var/lib/apt/lists/partial
mkdir -p ${TARGET}/var/cache/apt/archives/partial

rm -f ${TARGET}/etc/udev/rules.d/70-persistent-net.rules
rm -f ${TARGET}/etc/apt/sources.list
rm -f ${TARGET}/var/log/apt/*
rm -f ${TARGET}/var/log/dpkg.log*

cat <<EOT >${TARGET}/etc/fstab
# /etc/fstab: static file system information.
#
# Use 'blkid -o value -s UUID' to print the universally unique identifier
# for a device; this may be used with UUID= as a more robust way to name
# devices that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>             <dump>  <pass>
proc            /proc           proc    nodev,noexec,nosuid   0       0
EOT

cat <<EOT |ed -s ${TARGET}/etc/inittab >/dev/null
/tty2/
s/^/#/
/tty3/
s/^/#/
/tty4/
s/^/#/
/tty5/
s/^/#/
/tty6/
s/^/#/
wq
EOT

cat <<EOT >${TARGET}/etc/network/interfaces
auto lo
iface lo inet loopback
allow-hotplug eth0
iface eth0 inet dhcp
EOT

cat <<EOT >${TARGET}/etc/apt/apt.conf.d/02nocache
Dir::Cache {
  srcpkgcache "";
  pkgcache "";
}
EOT

cat <<EOT >${TARGET}/etc/apt/apt.conf.d/02compress-indexes
Acquire::GzipIndexes "true";
Acquire::CompressionTypes::Order:: "gz";
EOT

cat <<EOT >${TARGET}/etc/apt/apt.conf.d/02no-install-recommends
APT::Install-Recommends "0";
EOT

cat <<EOT >${TARGET}/etc/issue
Bachata Linux ${VERSION} \n \l

EOT

echo "Bachata Linux ${VERSION}" >${TARGET}/etc/issue.net

cat <<EOT |ed -s ${TARGET}/etc/motd.tail >/dev/null
0a
Welcome to Bachata Linux ${VERSION} (based on Debian GNU/Linux 6.0)

 * Home page: http://www.bachatalinux.net/
.
wq
EOT

chroot ${TARGET} localepurge-tiny

BUNDLE="bachatalinux-${VERSION}-${ARCH}-${KERNEL}.cgz"

(cd ${TARGET} && find . -type l -printf '%p %Y\n' | sed -n 's/ [LN]$//p' | xargs -rL1 rm -f)
(cd ${TARGET} && find . | cpio --quiet -o -H newc | gzip -9) >${BUNDLE}

rm -rf -- ${TARGET}

echo "Finished generating bundle ${BUNDLE}"

