#!/bin/sh

rm -rf /usr/share/man/*

rm -rf /usr/share/omf/*

rm -rf /usr/share/doc/kde/HTML/*

rm -rf /usr/share/gnome/help/*

for LOCALE in /usr/share/locale/*; do
    if [ -d ${LOCALE} ]; then
        if [ `basename ${LOCALE}` != en ]; then
            rm -rf ${LOCALE}/*
        fi
    fi
done

exit 0

